slam_toolbox:
  ros__parameters:
    mode: "mapping"  # Режим картографирования
    odom_frame: "odom"
    map_frame: "map"
    scan_topic: "/scan"  # Тема лидара
    transform_tolerance: 0.1
    use_sim_time: true
    map_update_interval: 5.0  # Интервал обновления карты
